"use client"

import { useState } from "react"

export default function Home() {
  const [file, setFile] = useState<File | null>(null)
  const [result, setResult] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)

  const handleCheck = async () => {
    if (!file) return

    setLoading(true)
    setResult(null)

    const controller = new AbortController
    const id = setTimeout(() => controller.abort(), 60000)

    const formData = new FormData
    formData.append('image', file)
    // Simulated AI detection
    const response = await fetch("http://127.0.0.1:5000/api/predict", {
      method: "post",
      body: formData,
      signal: controller.signal,
    })

    const data: { prediction: string, confidence: string } = await response.json()
    setResult(data.prediction === "real" ?
      `Im ${String(data.confidence).split(".")[1].slice(0, 2)}% sure this is Human-written ✍️`
      : `Im ${String(data.confidence).split(".")[1].slice(0, 2)}% sure this AI-generated 🤖`)
    setLoading(false)
  }

  return (
    <main className="">
      <div className="card">
        <h1 className="">
          AI Content Detector
        </h1>

        <p className="">
          Upload a file to check if it was generated by AI
        </p>

        <input
          type="file"
          onChange={(e) => setFile(e.target.files?.[0] || null)}
        />

        <button
          onClick={handleCheck}
          disabled={!file || loading}
          className=""
        >
          {loading ? "Analyzing..." : "Check File"}
        </button>

        {result && (
          <div className="result">
            {result}
          </div>
        )}
      </div>
    </main>
  )
}
